### ISSUE TITLE
Feature request: Return Arrow table in cursor result

### ISSUE THREAD

**Issue by daniel-thom** [Mause/duckdb_engine#1119]
Would you consider adding a method to return an Arrow table or Arrow record batches from a cursor result? My use case is that I want to convert a query result to a DataFrame as efficiently as possible. I can get this through Polars if I send the query as a string. It won't work if I send a sqlalchemy Selectable object. Example code and comments from a Polars developer are [here](https://github.com/pola-rs/polars/issues/19221).

**Comment by alexander-beedie** [comment]
@daniel-thom: FYI, I looked a little deeper here - seems it can already be done as there is a transparent redirect on the Cursor object to the underlying raw connection, which supports `fetch_arrow_table` and `fetch_record_batch` methods. I'll make Polars aware of the passthrough and then we can take full advantage of the Arrow speedups.
