### ISSUE TITLE
create_engine not working. Windows Path issue?

### ISSUE THREAD

**Issue by Alex-Monahan** [Mause/duckdb_engine#131]
Hello!

I am not able to get the create_engine function to work with a duckdb connection (in memory or otherwise). It seems like the error is related to not being able to find the name of the driver? I really appreciate your help!

I am on Windows, Python 3.7.1, SQLAlchemy 1.4.22, and duckdb 0.2.7 or 0.2.8.
`import sqlalchemy`
`sqlalchemy_engine = sqlalchemy.create_engine("duckdb:///:memory:")`

Then I get this traceback from Jupyter:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-0b980a005d38> in <module>
----> 1 sqlalchemy_engine = sqlalchemy.create_engine("duckdb:///:memory:",name='duckdb_engine')
      2 test_df = pd.read_sql("SELECT 'test' as test_string",sqlalchemy_engine)

<string> in create_engine(url, **kwargs)

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\deprecations.py in warned(fn, *args, **kwargs)
    296                         stacklevel=3,
    297                     )
--> 298             return fn(*args, **kwargs)
    299 
    300         doc = fn.__doc__ is not None and fn.__doc__ or ""

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\create.py in create_engine(url, **kwargs)
    520     u, plugins, kwargs = u._instantiate_plugins(kwargs)
    521 
--> 522     entrypoint = u._get_entrypoint()
    523     dialect_cls = entrypoint.get_dialect_cls(u)
    524 

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\url.py in _get_entrypoint(self)
    634         else:
    635             name = self.drivername.replace("+", ".")
--> 636         cls = registry.load(name)
    637         # check for legacy dialects that
    638         # would return a module with 'dialect' as the

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py in load(self, name)
    336                 return loader()
    337 
--> 338         for impl in compat.importlib_metadata_get(self.group):
    339             if impl.name == name:
    340                 self.impls[name] = impl.load

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py in importlib_metadata_get(group)
    117 
    118 def importlib_metadata_get(group):
--> 119     ep = importlib_metadata.entry_points()
    120     if hasattr(ep, "select"):
    121         return ep.select(group=group)

TypeError: entry_points() missing 1 required positional argument: 'name'

**Comment by Mause** [comment]
Are you able to tell me what version of `importlib_metadata` you have installed?

**Comment by Alex-Monahan** [comment]
I am on importlib_metadata 0.6!

Once again I really appreciate your help!

**Comment by Mause** [comment]
That version is too old for sqlalchemy, you'll need to update it

**Comment by Alex-Monahan** [comment]
Just updated and that fixed the issue! Thanks very much!
