### ISSUE TITLE
sqlalchemy queries using selectables fail when table has numeric columns

### ISSUE THREAD

**Issue by machow** [Mause/duckdb_engine#211]
Hey, I'm looking into duckdb support in siuba (https://github.com/machow/siuba/issues/379; cc @alex-monahan).

I ran into an issue when columns are Numeric--which seems to be a bug in some way the dialect is connected to postgres--but am a bit stumped about what could be happening.

It seems like:

* when a sqlalchemy selectable is used to query, a numeric result has coltype "NUMBER" in the cursor
* the cursor expects coltypes to be integers

**Example:**

Note that I ran this against sqlalchemy v1.4.29. It worked when the engine used postgres. I included working queries against a table with an integer column for contrast:

```python
import pandas as pd
import sqlalchemy as sqla

from sqlalchemy import create_engine

#engine = create_engine("postgresql://postgres:@localhost:5432/postgres")
engine = create_engine("duckdb:///:memory:")

# Case 1 (good): table with just integer column
df1 = pd.DataFrame({
    'x': [1,2,3],
})

# Case 2 (error): table with a float column
df2 = pd.DataFrame({
    "x": [1.1, 2.2, 3.3]
    })

df1.to_sql("df1", engine, index=False, if_exists="replace")
df2.to_sql("df2", engine, index=False, if_exists="replace")

# string query works fine ----

engine.execute("""SELECT x FROM df1""").fetchall()
engine.execute("""SELECT x FROM df2""").fetchall()

# sqlalchemy selectable queries

table1 = sqla.Table(
            "df1",
            sqla.MetaData(bind = engine),
            autoload_with = engine
            )

table2 = sqla.Table(
            "df2",
            sqla.MetaData(bind = engine),
            autoload_with = engine
            )

# succeeds
engine.execute(table1.select())

# fails: TypeError: %d format: a number is required, not str
engine.execute(table2.select())
```

edit:

I'm going further up the stack trace, and realizing that the bottom-most error message is actually an error that occurs during sqlalchemy error handling. Root error occurs in a call to sqlalchemy.engine.base.Connection._execute_context:

```
Binder Error: Macro function 'pg_get_constraintdef(constraint_oid, pretty_bool)' requires 2 positional arguments, but a single positional argument was provided.
LINE 4:                 pg_get_constraintdef(cons.oid) as src
```

**Comment by machow** [comment]
Digging deeper, pg_get_constraint is used in basically two methods:

* [`get_foreign_keys`](https://github.com/sqlalchemy/sqlalchemy/blob/689f2b910c5437a8d49ec9e69c9ba5035f0e9570/lib/sqlalchemy/dialects/postgresql/base.py#L3949). This is the method getting called and producing the error (since it calls pg_get_constraintdef with 2 arguments).
* [`get_check_constraints`](https://github.com/sqlalchemy/sqlalchemy/blob/689f2b910c5437a8d49ec9e69c9ba5035f0e9570/lib/sqlalchemy/dialects/postgresql/base.py#L4351)

Let me check a bit to see what cases might trigger `get_foreign_keys`....

**Comment by Alex-Monahan** [comment]
Thanks for taking a look at this!
Currently, DuckDB does not support Foreign Keys. Could that be the root cause of this issue?

[DuckDB Foreign Key Github Issue](https://github.com/duckdb/duckdb/issues/46)

**Comment by machow** [comment]
Ah thanks--yeah that makes sense. I think in the worst case having `get_foreign_keys` return a list might be a helpful stopgap.

But also weirdly, when I install this repo from master I don't see the error, so it seems like a unreleased change maybe fixed this? I looked through this code and am not sure what could have done it, though?!
