### ISSUE TITLE
set dialect name to match the one in the sqlalchemy URI

### ISSUE THREAD

**Issue by machow** [Mause/duckdb_engine#212]
Hey--thanks for duckdb_engine, it's been really straightforward to use!

One tricky piece with the dialect right now is that it's name is still set a "postgresql". What do you think of setting the name to "duckdb" in the dialect class, similar to how [python-bigquery-sqlalchemy does it](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/main/sqlalchemy_bigquery/base.py#L717)?

I forked and made the change for testing some stuff--happy to open a PR :)

https://github.com/machow/duckdb_engine/tree/feat-name-dialect

**Comment by Mause** [comment]
That would be great, please feel free to open a pr :)

**Comment by machow** [comment]
Hey--thanks for merging in #222! Any chance you'd be able to do a release? I was able to implement duckdb in siuba (https://github.com/machow/siuba/pull/422) thanks to `duckdb_engine`, and it's been working really well. Thanks for all the work you've put into this!

**Comment by Mause** [comment]
This is now released in 0.1.9 - please feel free to let me know if notice any further issues (and feel free to @ me, and then I'll get a notification on my phone)
