### ISSUE TITLE
Verify dialect layout against sqlalchemy docs

### ISSUE THREAD

**Issue by Mause** [Mause/duckdb_engine#275]
Finally found the official documentation for writing dialects: https://github.com/sqlalchemy/sqlalchemy/blob/main/README.dialects.rst

**Comment by machow** [comment]
Hey--I added a quick note in this PR

https://github.com/Mause/duckdb_engine/pull/274#issuecomment-1161813670

but one piece I noticed is different, is that sqlalchemy suggests registering the dialect class as the entrypoint, but here the module itself being registered: https://github.com/Mause/duckdb_engine/blob/master/pyproject.toml#L26
