### ISSUE TITLE
Support for unsigned integer types

### ISSUE THREAD

**Issue by cpcloud** [Mause/duckdb_engine#329]
We're adding support unsigned integer types to our SQL backends in ibis [here](https://github.com/ibis-project/ibis/pull/4259) and wanted to throw out the idea of duckdb_engine providing custom types specific to duckdb similar to the way some of the other sqlalchemy dialects like postgresql and mysql do.

**Comment by Mause** [comment]
Heya, I'd be very happy to accept a PR to add support for this!
