### ISSUE TITLE
[Bug]: Superset Error: (duckdb.IOException) IO Error: Could not set lock on file.

### ISSUE THREAD

**Issue by matsonj** [Mause/duckdb_engine#436]
### What happened?

(this might be the wrong repo - it looks like an issue with SQL Alchemy BUT this might also be an issue elsewhere)

When creating a dashboard with two charts on a single duckDB database, refreshing the dashboard gives the following error:
Error: (duckdb.IOException) IO Error: Could not set lock on file "/tmp/mdsbox.db": Resource temporarily unavailable. This looks like two reads on the same table at the same time.

As a workaround, refreshing each dashboard element one at a time (manually) does not reproduce the error. 

### DuckDB Engine Version

duckdb-engine 0.6.4

### DuckDB Version

duckdb 0.5.1

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Hi, can you link where you've raised this in the superset repository? And also the full stack trace?

**Comment by matsonj** [comment]
Hi @Mause - this was a config issue within superset, the default mode is an exclusive lock. So by adding ```{"connect_args":{"read_only":1}}```, I was able to allow multiple queries at once against a single duckdb database.

**Comment by matsonj** [comment]
Closing as resolved - config issue.
