### ISSUE TITLE
Superset with DuckDB engine parameters dialog gives error

### ISSUE THREAD

**Issue by sapcode** [Mause/duckdb_engine#482]
Dear @Mause,

we have installed the superset with the current helm chart and also installed the DuckDB engine, it shows now in the Databases Connections dropdown. The superset version in the right menu is shown as "Version: 0.0.0-dev".

When we create a new DuckDB database without engine parameter but with "Allow DML" and call SQL-Lab we are able to use the connection settings when executing as DML statements and the data is delivered correctly:

install 'httpfs';
load 'httpfs';
SET s3_endpoint='argo-artifacts:9000';
SET s3_access_key_id='XXX';
SET s3_secret_access_key='XXX';
SET s3_url_style = 'path';
SET s3_use_ssl=false;
select count(*) from 's3://raw/*.parquet';

However we don't want to provide the credentials in the SQL-Lab but would like to store them in the DuckDB Connector Advanced ENGINE PARAMETER dialog, we have tested the following parameter JSON strings but none of them seems to work:

Test1:
`{
	"engine_params": {
		 "connect_args":{
				"preload_extensions": ["httpfs"],
				"config": {
				  "s3_endpoint": "argo-artifacts:9000",
				  "s3_access_key_id": "XXX",
				  "s3_secret_access_key": "XXX",
				  "s3_url_style": "path",
				  "s3_use_ssl": "False"
		  }
		}
	}
}`

Test2:
`{
	 "connect_args":{
		"preload_extensions": ["httpfs"],
		"config": {
			  "s3_endpoint": "argo-artifacts:9000",
			  "s3_access_key_id": "XXX",
			  "s3_secret_access_key": "XXX",
			  "s3_url_style": "path",
			  "s3_use_ssl": "False"
		  }
	}
}`

We always get the same error:
**An error occurred while fetching databases: "Connection failed, please check your connection settings"**
In chrome debug we see:
PUT http://superset.mini.kube/api/v1/database/1 422 (UNPROCESSABLE ENTITY)
Response {type: 'basic', url: 'http://superset.mini.kube/api/v1/database/1'

When we remove the tag "engine_params" we get also the error:
File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute superset raise SupersetErrorsException(  superset superset.exceptions.SupersetErrorsException: [SupersetError(message="'str' object does not support item assignment", error_type=<SupersetErrorType.GENERIC_DB 

When looking at the core.py line 394 - 405 it looks like that "engine_params" is searched first, then "connect_args"
https://github.com/apache/superset/blob/master/superset/models/core.py

        params = extra.get("engine_params", {})
        if nullpool:
            params["poolclass"] = NullPool

        connect_args = params.get("connect_args", {})
        if self.impersonate_user:
            self.db_engine_spec.update_impersonation_config(
                connect_args, str(sqlalchemy_url), effective_username
            )

        if connect_args:
            params["connect_args"] = connect_args

In Connector Advanced ENGINE PARAMETER dialog, what is the specific connection string which need to be passed ? 
Are the any restrictions in usage of double " or single ' quotes in the JSON string ? 

Thank you very much!

**Comment by sapcode** [comment]
In superset log we can find the following entries:

superset superset.exceptions.SupersetErrorsException: [SupersetError(message="'str' object does not support item assignment", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERI │
│ superset 2022-12-09 10:22:57,995:WARNING:superset.views.base:[SupersetError(message="'str' object does not support item assignment", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR:  │
│ superset Traceback (most recent call last):                                                                                                                                                  
│ superset   File "/app/superset/views/base.py", line 241, in wraps                                                                                                                            
│ superset     return f(self, *args, **kwargs)                                                                                                                                                 
│ superset   File "/app/superset/utils/log.py", line 265, in wrapper                                                                                                                           
│ superset     value = f(*args, **kwargs)                                                                                                                                                      
│ superset   File "/app/superset/views/core.py", line 2408, in sql_json                                                                                                                        
│ superset     command_result: CommandResult = command.run()                                                                                                                                   
│ superset   File "/app/superset/sqllab/command.py", line 120, in run                                                                                                                          
│ superset     raise ex                                                                                                                                                                        │
│ superset   File "/app/superset/sqllab/command.py", line 102, in run                                                                                                                          
│ superset     status = self._run_sql_json_exec_from_scratch()                                                                                                                                 
│ superset   File "/app/superset/sqllab/command.py", line 157, in _run_sql_json_exec_from_scratch                                                                                              
│ superset     raise ex                                                                                                                                                                        │
│ superset   File "/app/superset/sqllab/command.py", line 152, in _run_sql_json_exec_from_scratch                                                                                              
│ superset     return self._sql_json_executor.execute(                                                                                                                                         
│ superset   File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute                                                                                                            
│ superset     raise SupersetErrorsException(                                                                                                                                                  
│ superset superset.exceptions.SupersetErrorsException: [SupersetError(message="'str' object does not support item assignment", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERI

**Comment by sapcode** [comment]
@Mause ok i debugged superset from dusk till down to finally found the following workaround:

1. Create DuckDB database with **empty** Engine Parameter + Activate Allow DML 
2. Open SQLLab and fire the 2 commands: install 'httpfs'; load 'httpfs'; 
3. Go back and Edit the DuckDB database Engine Parameter and this time paste in the full string:
{ "connect_args":{ "preload_extensions": ["httpfs"], "config": { "s3_endpoint": "argo-artifacts:9000", "s3_access_key_id": "XXX", "s3_secret_access_key": "XXX", "s3_url_style": "path", "s3_use_ssl": "False" } } }
4. Save the DuckDB database -> Now from this point onwards the SQL Lab will always use the Engine Parameter

So finally it looks like that the "preload_extensions" should install the httpfs if it's not present during the first database setup otherwise the add database dialog will not add the DuckDB database.

**Comment by sapcode** [comment]
@Mause can you approve https://github.com/Mause/duckdb_engine/pull/534 and take over the fix into the next release ?
conn.execute(f"INSTALL {extension}") before conn.execute(f"LOAD {extension}") otherwise the Superset dialog and advanced database properties will fail.

**Comment by sapcode** [comment]
@Mause can you approve https://github.com/Mause/duckdb_engine/pull/536 and take over the fix into the next release ?
We would propose to introduce a new array install_extensions like the preload_extensions and then the user's can choose what to install and what to preload ?

**Comment by Mause** [comment]
Thanks for the research you've done here, I appreciate it.

Unfortunately it very much looks to me like the errors are a result of bad handing of the exceptions thrown by DuckDB within superset, and are ultimately not something we can fix from this side (and extend beyond a simple case of an extension not being installed)

As far as automatically installing certain extensions, I believe DuckDB now has this built in. If you have issues with that functionality, please raise it in that repo
