### ISSUE TITLE
[Bug]: Column of type sqlalchemy.types.JSON returns string not object

### ISSUE THREAD

**Issue by criccomini** [Mause/duckdb_engine#504]
### What happened?

I have a column defined like:

```
from sqlalchemy.types import JSON
...
metadata_ = Column(
    'metadata',
    JSON,
    nullable=False,
)
```

When I read this column:

```
maybe_entry = session.scalar(select(Entry).where(
    ...
))
return maybe_entry.metadata_ if maybe_entry else None
```

The `metadata_` field comes back as a string. This is not how other dialects behave, notable Postgres, which I verified. I suspect duckdb-engine needs to take advantage of `json_serializer` and `json_deserializer` that are used in create_engine (and default to dumps/loads).

### DuckDB Engine Version

0.6.7

### DuckDB Version

0.6.1 (Python lib)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
I think the issue actually exists here in the DuckDB python library: https://github.com/duckdb/duckdb/blob/062fc98c5149584bf478546ed5b18c7930b08144/tools/pythonpkg/src/pyresult.cpp#L327

I'll try to find some time this week to fix this up

**Comment by Mause** [comment]
Okay, looks like I can fix this pretty easily here, I'll put up a pr now

**Comment by criccomini** [comment]
Awesome, thanks so much!

**Comment by criccomini** [comment]
@Mause I noticed that this query still fails with latest patch:

```
rows = session.execute(
                f"SELECT metadata FROM catalog WHERE {query}"
            ).fetchall()
```

In PG, `row[0]` is a dict. In duckdb-engine @ f4e900d7475f0fd901db89a6a3163559ee4fcc68, it returns a JSON-encoded string.

**Comment by criccomini** [comment]
Opening a new issue just to make things easier to track:

https://github.com/Mause/duckdb_engine/issues/507
