### ISSUE TITLE
Use with PyInstaller

### ISSUE THREAD

**Issue by davetapley** [Mause/duckdb_engine#508]
Just a heads up:

This will fail with ⬇️ in [PyInstaller](https://pyinstaller.org/).

```
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:duckdb
```

Workaround (from https://github.com/pyinstaller/pyinstaller/issues/7007#issuecomment-1201040976) is:

```
pyinstaller main.py --copy-metadata duckdb_engine --collect-submodules duckdb_engine
```

**Comment by Mause** [comment]
This sounds like something that might be better resolved by manually registering `duckdb_engine`, similar to how we do it in tests?

Like so:
```python
from sqlalchemy.dialects import registry

registry.register("duckdb", "duckdb_engine", "Dialect")
```
or perhaps actually explicitly importing the class and registering it?
