### ISSUE TITLE
Read only behavior for missing DB file

### ISSUE THREAD

**Issue by davetapley** [Mause/duckdb_engine#510]
_This issue probably merits some discussion, and I'm not sure there is even a sensible 'fix'_.

Consider this snippet using the `duckdb` Python package:

```py
duckdb.connect(database='missing.db'), read_only=True)
```

It will blow up with:
```
duckdb.CatalogException: Catalog Error: Cannot open database "missingd.db" in read-only mode: database does not exist
```

With this driver the equivalent would be:

```py
engine = create_engine("duckdb:///missing.db", connect_args={'read_only': True})
session = Session(bind=engine)
```

But that does not raise a `CatalogException` until you try to use the session, which can be misleading.
As a workaround one can call ⬇️ immediately after creating the `sessions`, but not ideal.
```py
session.connect()
```
---

I tried to see how SQLite behaves, but the only mention of read only is [here](https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#uri-connections) and with `sqlite:///missing.db?mode=ro` it didn't throw at all (which I think must be a bug there too?).

**Comment by Mause** [comment]
Just so I understand what you're asking for, you're expecting connection issues to be raised before you actually connect to the database?
