### ISSUE TITLE
[Bug]: some references to ipython-sql

### ISSUE THREAD

**Issue by idomic** [Mause/duckdb_engine#603]
### What happened?

A bug happened!
I think we can shift the dependency from `ipython-sql` to `jupysql`.
I found some [references](https://github.com/Mause/duckdb_engine/search?q=ipython-sql).
Happy to send a PR if that helps :)

### DuckDB Engine Version

NA

### DuckDB Version

NA

### Relevant log output

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Not sure this is a huge issue?
