### ISSUE TITLE
[Bug]: duckdb_engine doesn't work with sqlalchemy 2.0.11 and 2.0.12

### ISSUE THREAD

**Issue by cpcloud** [Mause/duckdb_engine#632]
### What happened?

The following code fails using SQLAlchemy 2.0.11 and 2.0.12:

```
In [2]: import sqlalchemy as sa

In [3]: eng = sa.create_engine("duckdb:///test.ddb")

In [4]: with eng.begin() as con:
   ...:     con.exec_driver_sql("CREATE TABLE t (x DOUBLE)")
   ...:     con.exec_driver_sql("INSERT INTO t VALUES (1.0), (2.0), (3.0)")

In [5]: md = sa.MetaData()

In [6]: t = sa.Table("t", md, autoload_with=eng)
/nix/store/36cy9gxv1g5wlpw939ad520kgmzwz01y-python3-3.10.10-env/lib/python3.10/site-packages/duckdb_engine/__init__.py:160: DuckDBEngineWarning: duckdb-engine doesn't yet support reflection on indices
  warnings.warn(

In [7]: with eng.begin() as con:
   ...:     con.execute(t.select())
```

The last stack frame looks like this:

```
File /nix/store/36cy9gxv1g5wlpw939ad520kgmzwz01y-python3-3.10.10-env/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/_psycopg_common.py:54, in _PsycopgNumeric.result_processor(self, dialect, coltype)
     51     return processors.to_float
     52 else:
     53     raise exc.InvalidRequestError(
---> 54         "Unknown PG numeric type: %d" % coltype
     55     )

TypeError: %d format: a real number is required, not str
```

where `coltype` is `'NUMBER'`.

### DuckDB Engine Version

0.7.0

### DuckDB Version

0.7.1

### SQLAlchemy Version

2.0.11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wcchang1115** [comment]
same here, can reproduce by below code snippet

Environment:
- duckdb-engine      0.7.0
- SQLAlchemy         2.0.11


```py
from sqlalchemy import create_engine, select, func, Float, text


def query():
    engine = create_engine("duckdb:///:memory:")

    with engine.connect() as conn:
        stmt = select(func.cast(text('1'), Float))
        result = conn.execute(stmt).fetchall()
        for row in result:
            print(row)


if __name__ == '__main__':
    query()
```

**Comment by cpcloud** [comment]
I wonder if it might be time to consider decoupling the dialect from psycopg2/postgres.

**Comment by Mause** [comment]
Finally found time to investigate this, and the issue here was a change in the psycopg2 dialect yeah.

Specifically, https://github.com/sqlalchemy/sqlalchemy/commit/c89c2b3d9a18bd0eb4c8ace50ef875101c9f4b70#diff-59574a708c2a4f1f07808fb00f3d26333891e8fb6d9e686694e51c6aa9909431R111

So yes, definitely another nail in the coffin. Especially since this `colspecs` field has been the source of so many issues raised lately, so the fix this time will be to stop using psycopg2's `colspecs` at the very least

**Comment by Mause** [comment]
Alright, release out - sorry for the delay folks 😅

**Comment by wcchang1115** [comment]
Thank you!
It works in my case.
