### ISSUE TITLE
[Bug]: Support hugeint type

### ISSUE THREAD

**Issue by popcornylu** [Mause/duckdb_engine#649]
### What happened?

In DuckDB, the type for `sum(integer)` is represented as `hugeint`. However, it appears that the current DuckDB engine does not support `hugeint` type.

The reproducible code

```
from sqlalchemy import create_engine, text, MetaData, Table
engine = create_engine("duckdb:///:memory:")
with engine.connect() as conn:
    conn.execute(text("create table t (v int)"))
    conn.execute(text("create table t2 as select sum(v) as s from t"))
    t2 = Table("t2", MetaData(), autoload_with=conn)
``` 

It warms `hugeint` cannot be recognized.

### DuckDB Engine Version

0.7.1

### DuckDB Version

0.7.1

### SQLAlchemy Version

2.0.10

### Relevant log output

```shell
/private/tmp/jaffle_shop/venv/lib/python3.10/site-packages/duckdb_engine/__init__.py:350: SAWarning: Did not recognize type 'hugeint' of column 's'
  columns = self._get_columns_info(rows, domains, enums, schema)  # type: ignore[attr-defined]
/private/tmp/jaffle_shop/venv/lib/python3.10/site-packages/duckdb_engine/__init__.py:160: DuckDBEngineWarning: duckdb-engine doesn't yet support reflection on indices
  warnings.warn(
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by popcornylu** [comment]
It works perfectly in `v0.7.2`. Thanks

**Comment by Mause** [comment]
> It works perfectly in `v0.7.2`. Thanks

Thanks for testing it out!
