### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by the21st** [Mause/duckdb_engine#71]
Hi there! Thanks for this adapter. I'd love to use it but I'm running on Python 3.7 – any chance you could release it for that version too or is there a blocker?

**Comment by Mause** [comment]
No blocker at all, give me a moment and I'll publish a fixed version

**Comment by Mause** [comment]
I just published 0.1.3, let me know if you have any more issues 💜

**Comment by the21st** [comment]
That's awesome, thank you!
