### ISSUE TITLE
[Bug]: Remove numpy from install dependencies

### ISSUE THREAD

**Issue by icemac** [Mause/duckdb_engine#724]
### What happened?

Even though DuckDB might often be used together with numpy it does not seem to be a necessary install dependency for this driver.
If numpy is not actually needed (like in my use case) it makes the installation process unnecessarily longer and more complicated.

So could it be removed from `pyproject.toml` and `poetry.lock`?
(I tried to come up with a PR but I failed as poetry was not longer able to install the pinned numpy version of 1.21.1.)

### DuckDB Engine Version

main

### DuckDB Version

0.8

### SQLAlchemy Version

2.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Numpy was actually a required dependency for DuckDB in older versions (which I still support), but is no longer. While I do support the change in theory, I'm aware that for some consumers there's a chance this will be a breaking change.

@cpcloud thoughts? Would Ibis be affected for example?

**Comment by cpcloud** [comment]
I don't think Ibis would be affected. Ibis has a hard dependency on numpy so removal of it in `duckdb_engine` shouldn't have any effect for us.
