### ISSUE TITLE
[Bug]: calling `.commit` causes results to be empty

### ISSUE THREAD

**Issue by edublancas** [Mause/duckdb_engine#734]
### What happened?

I noticed that calling `.commit()` on a connection makes existing results empty, this differs from duckdb's native behavior. Is this a bug or some expected behavior?

For context: in JupySQL, we have an autocommit mode that automatically `.commit()` after executing some SQL query, and I discovered this after debugging some bug reports.

Here's how to reproduce the issue:

```python
import duckdb
duckdb.__version__
```

    '0.8.1'

```python
import duckdb_engine
duckdb_engine.__version__
```

    '0.9.1'

```python
import sqlalchemy
sqlalchemy.__version__
```

    '2.0.19'

```python
conn_native = duckdb.connect()
engine = sqlalchemy.create_engine("duckdb://")
conn_engine = engine.connect()
```

```python
conn_native.execute("create table my_table (x INT)")
conn_native.execute("insert into my_table (x) VALUES (1), (2), (3)")
results = conn_native.execute("select * from my_table")
conn_native.commit()
print(results.fetchall())
```

    [(1,), (2,), (3,)]

```python
conn_engine.execute(sqlalchemy.text("create table my_table (x INT)"))
conn_engine.execute(sqlalchemy.text("insert into my_table (x) VALUES (1), (2), (3)"))
results = conn_engine.execute(sqlalchemy.text("select * from my_table"))
conn_engine.commit()
print(results.fetchall())
```

    []

### DuckDB Engine Version

0.9.1

### DuckDB Version

0.8.1

### SQLAlchemy Version

2.0.19

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Hey there, the maybe commit

**Comment by edublancas** [comment]
oh, right! I was able to reproduce this behavior by calling `.begin()` using the native connection, thanks!
