### ISSUE TITLE
[HELP]: Does duckdb_engine support Django's ORM

### ISSUE THREAD

**Issue by yoonghm** [Mause/duckdb_engine#735]
### What happened?

Has anyone try to use duckdb_engine within Django's ORM. I could not find any mention on this. Thanks.

### DuckDB Engine Version

Have not used 

### DuckDB Version

0.8.0

### SQLAlchemy Version

Not yet used

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
No, duckdb-engine is only an SQLAlchemy driver
