### ISSUE TITLE
[Bug]: the timestamp type in a table, use duckdb_engine to get,  return object

### ISSUE THREAD

**Issue by linbendatarho** [Mause/duckdb_engine#738]
### What happened?

CREATE TABLE my_table (id INTEGER, ts TIMESTAMP)
INSERT INTO my_table VALUES (1, '2023-07-15 12:34:56')

SELECT date_trunc('month', ts::TIMESTAMP) as month FROM my_table

use native duckdb to execute the sql , i get "month" as 'datetime' type

use duckdb_engine, i get "month" as 'object' type, it's a bug

### DuckDB Engine Version

0.9.2

### DuckDB Version

>=0.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Can you please provide the Python code that you are running?

**Comment by linbendatarho** [comment]
native duckdb
```
import duckdb
import pandas as pd

conn = duckdb.connect(database=':memory:')

conn.execute("CREATE TABLE my_table (id INTEGER, ts TIMESTAMP)")
conn.execute("INSERT INTO my_table VALUES (1, '2023-07-15 12:34:56')")

mytable =conn.execute("SELECT * as aa FROM my_table").fetchdf()

data = conn.execute("SELECT date_trunc('month', ts::TIMESTAMP) as aa FROM my_table").fetchdf()

print(data.dtypes["aa"])
```

duckdb_engine
```
from sqlalchemy import create_engine
import sqlalchemy as sa

eng = create_engine("duckdb:///:memory:").connect()
eng.execute(sa.text("CREATE TABLE my_table (id INTEGER, ts TIMESTAMP)"))
eng.execute(sa.text("INSERT INTO my_table VALUES (1, '2009-01-01T00:00:00.000')"))
data = pd.read_sql("SELECT datetrunc('month', ts) aa FROM my_table", eng)
print(data.dtypes["aa"])
```
results are not same

**Comment by Mause** [comment]
For whatever reason, pandas doesn't automatically load `datetime.date` as a date type. Not sure why.

You can tell it to interpret a given column a date like so though:
```py
data = pd.read_sql("SELECT datetrunc('month', ts) aa FROM my_table", eng, parse_dates=['aa'])
```
