### ISSUE TITLE
Cannot connect with database file via duckdb

### ISSUE THREAD

**Issue by caohaisil201** [Mause/duckdb_engine#770]
I'm trying to connect Superset to a DuckDB database file. I receive the following error:

```
superset_app           | Traceback (most recent call last):
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset_app           |     rv = self.dispatch_request()
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
superset_app           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app           |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset_app           |     return f(self, *args, **kwargs)
superset_app           |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app           |     raise ex
superset_app           |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app           |     duration, response = time_function(f, self, *args, **kwargs)
superset_app           |   File "/app/superset/utils/core.py", line 1523, in time_function
superset_app           |     response = func(*args, **kwargs)
superset_app           |   File "/app/superset/utils/log.py", line 255, in wrapper
superset_app           |     value = f(*args, **kwargs)
superset_app           |   File "/app/superset/views/base_api.py", line 93, in wraps
superset_app           |     return f(self, *args, **kwargs)
superset_app           |   File "/app/superset/databases/api.py", line 918, in test_connection
superset_app           |     TestConnectionDatabaseCommand(item).run()
superset_app           |   File "/app/superset/databases/commands/test_connection.py", line 195, in run
superset_app           |     raise SupersetErrorsException(errors) from ex
superset_app           | superset.exceptions.SupersetErrorsException: [SupersetError(message='(builtins.NoneType) None\n[SQL: (duckdb.IOException) IO Error: Extension "/root/.duckdb/extensions/v0.8.1/linux_amd64_gcc4/sqlite_scanner.duckdb_extension" not found.\nExtension "sqlite" is an existing extension.\n\nInstall it first using "INSTALL sqlite".\n(Background on this error at: https://sqlalche.me/e/14/e3q8)]\n(Background on this error at: https://sqlalche.me/e/14/dbapi)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'DuckDB', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```

**Screenshot**
<img width="1440" alt="Screen Shot 2023-09-05 at 17 56 26" src="https://github.com/Mause/duckdb_engine/assets/62064861/bf4912a8-97e0-4496-9008-d095883fde76">

I also add the extra parameters like this but get the same issue
<img width="1440" alt="Screen Shot 2023-09-05 at 17 56 58" src="https://github.com/Mause/duckdb_engine/assets/62064861/30f5a8d1-cf81-488f-bc7f-963f9a0720e3">

**How to procedure**

1. Goto Data -> Connect database
2. Click + Database button
3. Enter requirements field
4. Click "TEST CONNECTION" / "CONNECT" button

**Library version**

duckdb=0.8.1  
duckdb-engine=0.9.2  
SQLAlchemy=1.4.36  

**Checklist**  
- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.  
- [x] I have reproduced the issue with at least the latest released version of superset.  
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.  

**Code of Conduct**
- [x] I agree to follow this project's Code of Conduct

Thank you very much!

**Comment by Mause** [comment]
Sounds like you're trying to open a SQLite database file with DuckDB without having the SQLite extension installed. If you install it, using the instructions in the error message, that should resolve the issue

**Comment by caohaisil201** [comment]
It feels like I create a new duckdb first with uri is duckdb:///:memory:, then go to sqllab and run the [command](https://duckdb.org/docs/guides/import/query_sqlite) below
```
INSTALL sqlite;
LOAD sqlite;
```
Did I misunderstand it? I want to connect with SQLite database file at first but not have to connect with uri memory above. Is there other way to do follow by the instructions?

**Comment by Mause** [comment]
If you run the installation once that will work for all the future uses with that DuckDB version. You can use the ATTACH statement instead if you want though
