### ISSUE TITLE
Which is the supported syntax for parameterized queries?

### ISSUE THREAD

**Issue by obi1kenobi** [Mause/duckdb_engine#796]
Thanks for building and maintaining this awesome library! Quick question on a speed bump I ran into.

I see that parameterized queries are supported, since query parameters are passed to `duckdb` here: https://github.com/Mause/duckdb_engine/blob/e7b34e727f62e4d45279130a3f422097f307e52c/duckdb_engine/__init__.py#L144

However, I can't seem to figure out neither via docs nor via trial and error which is the correct syntax to use here. Everything I've tried raises an error like `duckdb.duckdb.ParserException: Parser Error: syntax error at or near ":"`. Parameterized argument syntax I've tried:
- `:arg`
- `$1`
- `%s`
- `%(var_name)s`
- `?`

The [duckdb docs](https://duckdb.org/docs/api/python/dbapi#querying) say that multiple of these options should be supported, but so far I haven't been able to get them to work using a fresh installation of `duckdb_engine v0.9.2`.

**Comment by Mause** [comment]
Hey @obi1kenobi , the SQLAlchemy tutorial covers this pretty well: https://docs.sqlalchemy.org/en/14/core/tutorial.html#using-textual-sql

For example:
```python
s = text("SELECT :x")
assert [('m',)] == engine.execute(s, {"x": "m"}).fetchall()    
```

**Comment by obi1kenobi** [comment]
Distilled down from the failing test case in the linked PR:
```python
from sqlalchemy import *

metadata_obj = MetaData()

event.listen(metadata_obj, "before_create", schema.CreateSchema("schema_a"))

user = Table(
    "anything",
    metadata_obj,
    Column("id", Integer, Sequence("id_seq"), primary_key=True),
    schema="schema_a",
)

engine = create_engine("duckdb:///:memory:")
metadata_obj.create_all(engine)

# This runs fine.
with engine.begin() as connection:
    cursor = connection.execute(text("SELECT 1;"))
    print(cursor.fetchall())

# This block fails.
with engine.begin() as connection:
    # Attempting to select a schema causes the parse error I mentioned.
    connection.exec_driver_sql("SET search_path TO :schema", {"schema": "schema_a"})
    
    # These lines never run.
    cursor = connection.execute(text("SELECT 1;"))
    print(cursor.fetchall())
```

This is with `duckdb-engine == "0.9.2"` on any of Python 3.8 - 3.11. This is the [full lockfile](https://github.com/langchain-ai/langchain/blob/289de601c822bbbe62593f5c3c759d58c755fcfd/libs/langchain/poetry.lock) in case any other installed versions are relevant.

**Comment by obi1kenobi** [comment]
It turns out `connection.execute()` runs into the same problem. Here's another snippet with `exec_driver_sql()` removed and replaced with `.execute()`:

```python
from sqlalchemy import *

metadata_obj = MetaData()

event.listen(metadata_obj, "before_create", schema.CreateSchema("schema_a"))

user = Table(
    "anything",
    metadata_obj,
    Column("id", Integer, Sequence("id_seq"), primary_key=True),
    schema="schema_a",
)

engine = create_engine("duckdb:///:memory:")
metadata_obj.create_all(engine)

# This runs fine.
with engine.begin() as connection:
    cursor = connection.execute(text("SELECT 1;"))
    print(cursor.fetchall())

# This block fails.
with engine.begin() as connection:
    # Attempting to select a schema causes the parse error below.
    connection.execute(text("SET search_path TO :schema"), {"schema": "schema_a"})
    
    # These lines never run.
    cursor = connection.execute(text("SELECT 1;"))
    print(cursor.fetchall())
```

The error is this:
```
File .../.venv/lib/python3.11/site-packages/duckdb_engine/__init__.py:142, in ConnectionWrapper.execute(self, statement, parameters, context)
    140         self.__c.execute(statement)
    141     else:
--> 142         self.__c.execute(statement, parameters)
    143 except RuntimeError as e:
    144     if e.args[0].startswith("Not implemented Error"):

ProgrammingError: (duckdb.duckdb.ParserException) Parser Error: syntax error at or near "?"
LINE 1: SET search_path TO ?
                           ^
[SQL: SET search_path TO ?]
[parameters: ('schema_a',)]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

It seems that `sqlalchemy` is applying `qmark` syntax for parameterized queries, but the driver still seems to not like it.

**Comment by Mause** [comment]
Okay, I've been missing the actual root cause here - DuckDB simply doesn't support parameterized SET queries. Feel free to raise a feature request in the DuckDB repo - https://github.com/duckdb/duckdb/discussions/categories/ideas

**Comment by obi1kenobi** [comment]
Thanks for looking into it, much appreciated!
