### ISSUE TITLE
How to reuse same in-memory connection?

### ISSUE THREAD

**Issue by graup** [Mause/duckdb_engine#812]
### What happened?

I think this may be related to #338. Or maybe I'm just severely misunderstanding something.

I'm trying to use duckdb for testing. The application code uses sqlalchemy, so I thought I can just pass `duckdb:///:memory:` as the db url, pre-populate the in-memory db with some data, and then run my tests against that database.

However, it seems that a new database is created every time an sqlalchemy engine is created.

Example code:

```python
import sqlalchemy as sa

engine = sa.create_engine("duckdb:///:memory:")
with engine.connect() as conn:
    conn.execute(sa.text(f"CREATE TABLE test AS SELECT 1"))
    print(conn.execute(sa.text("SELECT * FROM test")).fetchall())

# <sqlalchemy.engine.cursor.CursorResult object at 0xffffa8169ef0>
# [(1,)]

engine = sa.create_engine("duckdb:///:memory:")
with engine.connect() as conn:
    print(conn.execute(sa.text("SELECT * FROM test")).fetchall())

# duckdb.duckdb.CatalogException: Catalog Error: Table with name test does not exist!
```

I also tried using different pools (StaticPool), but it doesn't help.

Is there any way to do this?

### DuckDB Engine Version

0.9.2

### DuckDB Version

0.9.1

### SQLAlchemy Version

2.0.19

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by graup** [comment]
Actually, this doesn't even work when I set a database file (replacing `:memory:` with `test.db`) so it's not an issue of the connection pool. I must be understanding something wrong about Duckdb 😕

**Comment by graup** [comment]
Sorry for the noise. My mistake was that I forgot to `conn.commit()` after inserting the data.

**Comment by Mause** [comment]
> However, it seems that a new database is created every time an sqlalchemy engine is created.

This is correct - a `:memory:` database exists only in memory, once you close it (by closing the connection, or the engine) it disappears.

> Sorry for the noise. My mistake was that I forgot to conn.commit() after inserting the data.

No worries :)
