### ISSUE TITLE
[Bug]: Subtracting timestamps results in "OverflowError: Python int too large to convert to C int"

### ISSUE THREAD

**Issue by goto-loop** [Mause/duckdb_engine#872]
### What happened?

With certain datetime values, the operation `CAST('<timestamp1>' AS TIMESTAMP) - CAST('<timestamp2>' AS TIMESTAMP)` throws an error: `OverflowError: Python int too large to convert to C int`. Here's a minimal working example:

```python
from sqlalchemy import create_engine, text

conn = create_engine("duckdb:///:memory:").connect()

query = "SELECT CAST('2023-07-22T11:28:07' AS TIMESTAMP) - CAST('2023-07-23T11:28:07' AS TIMESTAMP)"
result = conn.execute(text(query))

for row in result:
    print(row)
```
However, it doesn't happen with all datetime values: replace the query with e.g. `"SELECT CAST('2023-07-22T11:28:07' AS TIMESTAMP) - CAST('2023-07-22T16:46:21' AS TIMESTAMP)"` and the error is gone.

I've encountered this bug while using Superset with DuckDB and DuckDB Engine. I know it's quite specific and I'm also not completely sure if it's a DuckDB Engine or SQLAlchemy issue (it's not a DuckDB issue though because there the query executes just fine).

### DuckDB Engine Version

0.10.0

### DuckDB Version

0.9.2

### SQLAlchemy Version

2.0.25

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Hey there! Thanks for raising this issue, however it does appear to be an issue in DuckDB, I'm not sure why you were unable to reproduce it there:

```py
import duckdb

conn = duckdb.connect(':memory:')
conn.execute("SELECT CAST('2023-07-22T11:28:07' AS TIMESTAMP) - CAST('2023-07-23T11:28:07' AS TIMESTAMP)")
conn.fetchall()
```

Can you please raise it in the DuckDB repo instead?
