### ISSUE TITLE
[Bug]: Integer and Float have same DBAPI type

### ISSUE THREAD

**Issue by b-schmeling** [Mause/duckdb_engine#886]
### What happened?

When I fetch the DBAPI types from `result.cursor.description`, there is no difference between an Integer and a Double. Because of that, I have to query `information_schema.columns` in order to get detailed type information. 

With other databases, when I use `result.cursor.description` they seem to return their internal type codes. E.g. postgres returns something with the format `(Column(name='a', type_code=23), Column(name='b', typ..._code=701))`

On the [PEP 249 standard](https://peps.python.org/pep-0249/#type-objects), the type codes should be "equal" to one their Type Objects, not identical.
> The type_code must compare equal to one of Type Objects defined below. Type Objects may be equal to more than one type code (e.g. DATETIME could be equal to the type codes for date, time and timestamp columns; see the [Implementation Hints](https://peps.python.org/pep-0249/#implementation-hints) below for details).

I believe that the type codes are meant to cover the full range of internal DB types.

Repro: 
```python
import sqlalchemy
from sqlalchemy.sql import text

if __name__ == "__main__":
    engine = sqlalchemy.create_engine(
        "sqlite:///:memory:",
    )
    with engine.begin() as conn:
        conn.execute(text("CREATE TABLE test (a INTEGER, b DOUBLE)"))
        conn.execute(text("INSERT INTO test VALUES (1, 1.1)"))

        result = conn.execute(text("SELECT * FROM test"))

        metadata = result.cursor.description

        print(metadata)

```

Prints: `[('a', 'NUMBER', None, None, None, None, None), ('b', 'NUMBER', None, None, None, None, None)]`

### DuckDB Engine Version

0.10.0

### DuckDB Version

0.9.2

### SQLAlchemy Version

2.0.25

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
I'm not sure why you've raised this bug here, this is an issue in DuckDB itself, not this SQLAlchemy driver. Feel free to raise it upstream: https://github.com/duckdb/duckdb

**Comment by tboddyspargo** [comment]
Opened on duckdb as https://github.com/duckdb/duckdb/issues/10495
