### ISSUE TITLE
Support for asyncio

### ISSUE THREAD

**Issue by leestorm4520** [Mause/duckdb_engine#898]
At the moment, duckdb-engine only supports non-async I/O. Could you add async driver as well? I think it's gonna touch lots of code but it would boost  performance a lot

**Comment by Mause** [comment]
Given DuckDB itself isn't Async, this probably isn't a worthwhile exercise.

I'd recommend looking at the async support in sqlalchemy itself instead: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html
