### ISSUE TITLE
[Feature request]: How to hive query parquet files?

### ISSUE THREAD

**Issue by xor2003** [Mause/duckdb_engine#961]
### What happened?

How to execute the following code from duckdb guide using ORM?
```
SELECT *
FROM read_parquet('orders/*/*/*.parquet', hive_partitioning = true)
WHERE year = 2022 AND month = 11;
```

### DuckDB Engine Version

latest

### DuckDB Version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Hi there! What have you tried so far?

**Comment by xor2003** [comment]
Actually this feature is supported by DuckDB. So might be not so complex to implement or just not clear how to query
